---

- name: Ensure an ansible-galaxy requirements.yml file contains a list of roles
  template:
    src: requirements.yml.j2
    dest: "{{ controller_ansible_tmp_requirements_path }}"

- name: Ensure ansible roles are installed using ansible-galaxy
  command: "ansible-galaxy install -f -r {{ controller_ansible_tmp_requirements_path }}"
  environment:
    ANSIBLE_ROLES_PATH: "{{ playbook_dir }}/../roles/"
  changed_when: false
