---

- name: Ensure Slack Repository key exists
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present

- name: Ensure APT repository file exists
  apt_repository:
    repo: "deb https://packagecloud.io/slacktechnologies/slack/{{ ansible_distribution | lower }}/ {{ ansible_distribution_version | lower }} main"
    state: present
    filename: slack

- name: Ensure Slack is installed
  apt:
    name: slack
    state: present
    update_cache: true
